### ISSUE TITLE
No configurable types returned for some planning groups

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas_fab#129]
When using `robot.get_configurable_joint_types()` with the Panda model loaded, one (`panda_arm_hand`) out of the existing 3 planning groups returns an empty list.  

## Expected Result
```
>>> robot.get_configurable_joint_types('panda_arm_hand')
[0, 0, 0, 0, 0, 0, 0, 2]
```

## Actual Result
```
>>> robot.get_configurable_joint_types('panda_arm_hand')
[]
```

## Reproduction Steps
1. Load panda demo planner
2. Load the robot from ROS using the ROS loader examples
3. Use the line above to get configurable joint types

## System Information

- `compas_fab`: `0.10.2`

**Comment by romanarust** [comment]
fixed through 0db431ef7604c6a8c11737f80e139535167275da
