### ISSUE TITLE
Generic path planning API

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas_fab#14]
Improve path planning API to allow more backends to be pluged-in (besides MoveIt and V-REP).

**Comment by yijiangh** [comment]
I'd vote for supporting ROS-I's [descartes](https://github.com/ros-industrial-consortium/descartes) package too. Descartes does semi-constrained cartesian planning, which is very common in most of the planning problems we encounter in robotic fabrication applications (users usually specify end effector poses and want to find a feasible joint trajectory to connecting these EE poses with either free movement or linear movement). A nice paper by De Maeyer et al. 2017 [1] documented the algorithm used in descartes.

The core algorithm used by [Choreo](https://github.com/yijiangh/Choreo)'s [semi-constrained Cartesian planner](https://arxiv.org/pdf/1810.00998.pdf) is essentially a generalized version of descartes' joint graph search algorithm, to make it possible to deal with problems with large planning horizon. The development of this algorithm resulted from active discussion with descartes' developers, see [here](https://github.com/ros-industrial-consortium/descartes/issues/200) and [here](https://github.com/ros-industrial-consortium/descartes/issues/55).

[1] De Maeyer, J., Moyaers, B., Demeester, E.: Cartesian path planning for welding robots: Evaluation of the descartes algorithm. In: Proceedings of the 2017 22nd IEEE International Conference on Emerging Technologies and Factory Automation (2017). [Paper link](https://ieeexplore.ieee.org/document/8247616)
