### ISSUE TITLE
Spherical Wrist Kinematics

### ISSUE THREAD

**Issue by romanarust** [compas-dev/compas_fab#162]
# Feature Request

Spherical Wrist Kinematics solver for robots with spherical wrist (ABB, Staubli)

Useful links:
* https://github.com/Jmeyer1292/opw_kinematics
* https://www.researchgate.net/publication/264212870_An_Analytical_Solution_of_the_Inverse_Kinematics_Problem_of_Industrial_Serial_Manipulators_with_an_Ortho-parallel_Basis_and_a_Spherical_Wrist
* https://github.com/visose/Robots/blob/master/Robots/Kinematics.cs

**Comment by romanarust** [comment]
in the making ...
https://github.com/compas-dev/compas_fab/blob/ik_analytical/src/compas_fab/backends/ik_solver/ik_spherical_wrist.py

**Comment by gonzalocasas** [comment]
Solved already
