### ISSUE TITLE
Change coord to coordinates in compas_fab.robots.robot.to_local_coords & to_world_coords

### ISSUE THREAD

**Issue by tetov** [compas-dev/compas_fab#175]
Change coords to coordinates in `compas_fab.robots.robot.to_local_coords` & `.to_world_coords` to use the same convention as compas [0.16](https://github.com/compas-dev/compas/blob/master/CHANGELOG.md#0160-2020-06-05).

It's just two methods but they are in a lot of the documentation and examples. Maybe keep `*_coords` with a deprecation warning?

**Comment by tetov** [comment]
Tightly related to #171.

**Comment by gonzalocasas** [comment]
#171 covers all the changes needed to bump to 0.16, so I'll close this
