### ISSUE TITLE
Neutral language refactoring

### ISSUE THREAD

**Issue by beverlylytle** [compas-dev/compas_fab#184]
In line with the code of conduct, `compas_fab` should maintain current standards for neutral language.  In particular,`ros_master` should be renamed to `ros_core` wherever possible, the `master` branch should be renamed in accordance with GitHub's new standard, the promotional slides for `compas_fab` should be adapted, and any other non-neutral language in code or examples should be changed.

**Comment by gonzalocasas** [comment]
ROS is changing to `main` as well: https://discourse.ros.org/t/consider-renaming-default-branches/15385/6

**Comment by beverlylytle** [comment]
But from what I could tell in that discussion, it was only about git branch names, which I think effects us not at all.

**Comment by gonzalocasas** [comment]
True, there was only a passing mention of the ros-master, but that is because ROS2 got rid of master/slave already. As far as I can tell, the removal was not related to neutral language, but more a side effect of the new `DDS` service used to coordinate nodes, but nevertheless, it did go away.

**Comment by gonzalocasas** [comment]
Github's default branch will change to `main` starting 1st October, and apparently (as reported by [zdnet](https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/)), by the end of the year, they will have tools/features to make it seamless to update for existing repos.

**Comment by beverlylytle** [comment]
This exists now: https://docs.github.com/en/github/administering-a-repository/renaming-a-branch

**Comment by gonzalocasas** [comment]
Done! 
ROS-specific updates to be done on #272
