### ISSUE TITLE
scaling in add_attached_collision_mesh modified the underlying mesh

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas_fab#186]
I encountered a problem recently where repeatedly calling the `add_attached_collision_mesh ` function with the same `mesh` object causes the acm to disappear. And I pinned the cause to this line where the scale function causes an undocumented side effect. 

https://github.com/compas-dev/compas_fab/blob/e4bfe769103aa41ff8beb823864245a4a6d82785/src/compas_fab/robots/planning_scene.py#L231

As a feature suggestion, I think it is more robust if the line uses `scaled`. This allows users to reuse the input mesh object for other purpose such as visualization or in my case not having problem when calling the function repeatedly.

The behavior of this function with the Moveit planner is that the new `acm` replaces the old one if the id is the same. I think it is better to document this. At the moment, it is ambiguous if user should call `RemoveAttachedCollisionMesh` before calling `add_attached_collision_mesh`. From what I have tested (and also @matteo-pacher  told me) it is not necessary.

**Comment by romanarust** [comment]
Good point!
