### ISSUE TITLE
Is the `group` in `options` missing in `plan_cartesian_motion`

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas_fab#189]
I see there is this new implementation of `plan_cartesian_motion` that has the `options` dictionary, And the following lines seems to be extract things from that `options` dict, is there any chance the `group` parameter is forgotten?

https://github.com/compas-dev/compas_fab/blob/f54d5bb4af975c523f8cffe9adaeab9a024c854b/src/compas_fab/robots/robot.py#L1210-L1220

**Comment by beverlylytle** [comment]
`group` is left as an argument on the same level as `options`, not as a value within `options`.  It's passed in line 1218.

**Comment by yck011522** [comment]
Hum.. yes you are right.... so maybe something else is off...

I'm trying to plan with one planning group (rfl's robot12_YZ) and the planner is giving me an error about robot11....

![2020-08-18 16_13_07](https://user-images.githubusercontent.com/1297653/90527239-9c6a7d00-e171-11ea-850e-d449bf3e7fd2.png)

**Comment by beverlylytle** [comment]
After discussion with @yck011522 , it was determined that the end effector for the main planning group was always being passed along in the request rather than the end effector for the specified group.
