### ISSUE TITLE
Cannot import helpers from compas_rhino (version issue?)

### ISSUE THREAD

**Issue by philianeles** [compas-dev/compas_fab#210]
**Describe the bug**
cannot import helpers from compas_rhino

**To Reproduce**
1. Context: Rhino 6, Grasshopper
2. Sample script: see screen shot
3. Sample data: -
4. See error: see screen shot

**Expected behavior**
import helpers from compas_rhino

**Screenshots**
![image](https://user-images.githubusercontent.com/11179066/93763994-a1a86500-fc12-11ea-8cd6-7212b274791f.png)

**Desktop:**
 - OS: Windows 10
 - Python version 3.7
 - Python package manager conda

**Comment by gonzalocasas** [comment]
@philianeles yes, this is definitely a version issue (`compas_rhino.helpers` is gone in the 0.16.2 release). The latest `compas_fab` from the main branch runs correctly against `compas 0.16.2`.

**Comment by philianeles** [comment]
@gonzalocasas thanks! it works.
