### ISSUE TITLE
robot model update with attached tool is wrong

### ISSUE THREAD

**Issue by kathrindoerfler** [compas-dev/compas_fab#216]
**Describe the bug**

Found a bug in:
https://github.com/compas-dev/compas_fab/blob/165a7f379c4817e077f2182fb98a90aa953a21e5/src/compas_fab/artists/base.py#L77

In the robot artist in the method update(), the selected transformation to compute the tool transform seems to be hardcoded with transformations[names[-1]], and is therefore only correct in special cases.

if self.attached_tool:
    self._apply_transformation_on_transformed_link(self.attached_tool, transformations[names[-1]])

This should be changed, so that the joint can either be specified or is chosen correctly automatically.

**Comment by beverlylytle** [comment]
`RobotModelArtist` is in the process of moving from `compas_fab` to `compas`.  In the new `RobotModelArtist` of `compas`, I believe this should be fixed.  You can check out the code [here](https://github.com/compas-dev/compas/blob/master/src/compas/robots/base_artist/_artist.py).
