### ISSUE TITLE
Slowness in drawing robot frames in robot_playground

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas_fab#230]
**Describe the bug**
When I tried to visualize a big robot model in GH, and turnning frams on. It is very slow.
![2020-10-22 15_03_57](https://user-images.githubusercontent.com/1297653/96876379-ac0b8800-1478-11eb-9442-14c416e339cc.jpg)
![2020-10-22 15_03_42](https://user-images.githubusercontent.com/1297653/96876383-aca41e80-1478-11eb-9487-73a5d2878d3c.jpg)

**Comment by gonzalocasas** [comment]
This should be fixed via #649 since it was the same underlying problem.
