### ISSUE TITLE
Documentation for Rhino and GHPython artist classes are missing.

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas_fab#231]
**Describe the bug**
Documentation for Rhino and GHPython artist classes are missing.
![2020-10-22 15_22_15](https://user-images.githubusercontent.com/1297653/96877830-6e0f6380-147a-11eb-96c9-0ae81dd8a34c.jpg)
![2020-10-22 15_22_05](https://user-images.githubusercontent.com/1297653/96877833-6ea7fa00-147a-11eb-8a3a-b0e695836414.jpg)

**Comment by beverlylytle** [comment]
Yes, these are missing because the artists have been moved to compas.  The docs for the robot artists in compas probably should be looked at again, and a deprecation warning should be given here.

**Comment by gonzalocasas** [comment]
Updated these pages with links to the new compas artists: https://gramaziokohler.github.io/compas_fab/latest/reference/compas_fab.rhino.html
