### ISSUE TITLE
'Configuration' object has no attribute 'keys'

### ISSUE THREAD

**Issue by philianeles** [compas-dev/compas_fab#244]
**Describe the bug**
I have upgraded to 0.12.0 from 0.11.2 and I am having the below error with Configuration.

**To Reproduce**
1. Context: Rhino 6, Grasshopper
2. Sample script (see below)
3. Sample data
![image](https://user-images.githubusercontent.com/11179066/98787082-52570780-23ff-11eb-9191-b43449708370.png)

4. See error:
```
Runtime error (MissingMemberException): 'Configuration' object has no attribute 'keys'

Traceback:
  line 249, in _update, "C:\Users\sercan\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\compas\robots\base_artist\_artist.py"
  line 683, in compute_transformations, "C:\Users\sercan\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\compas\robots\model\robot.py"
  line 244, in update, "C:\Users\sercan\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts\compas\robots\base_artist\_artist.py"
  line 134, in update_model, "<string>"
  line 148, in script
```

**Desktop:**
 - OS: Windows 10
 - Python version 3.7
 - Python package manager conda

**Comment by gonzalocasas** [comment]
@philianeles i think you need to change the line 134 from `robot.artist.update` to the new `robot.update` and the error will go away.

**Comment by gonzalocasas** [comment]
and you'll need to remove the `names` parameter as well (i think)

**Comment by philianeles** [comment]
it worked with changing the `robot.artist.update` to `robot.update`, thank you @gonzalocasas!
