### ISSUE TITLE
Bump dependency to (upcoming) COMPAS 1.0

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas_fab#258]
COMPAS is going to reach 1.0 in the coming days. We need to bump the dependency in FAB accordingly as soon as 1.0 is available, and in the meantime, this could be tested against `main` branch of compas repo.

**Comment by beverlylytle** [comment]
the `main` branch?

**Comment by gonzalocasas** [comment]
It will be correct, eventually 😛

**Comment by beverlylytle** [comment]
oh ok, didn't know if i missed something.
