### ISSUE TITLE
robot.get_configurable_joints() returns also mimicking joints 

### ISSUE THREAD

**Issue by romanarust** [compas-dev/compas_fab#262]
**Describe the bug**
As a user I expect that `robot.get_configurable_joints()` returns only joints that can be controlled. If my robot has a gripper with 4 prismatic joints and 3 of them are mimicking the 4th, then this is the only "configurable" one.
At the moment this function returns all 4 of them.

**Comment by gonzalocasas** [comment]
Shouldn't this be filtered already at the `compas.robots.RobotModel` level? Mimic joints could be excluded in the `Joint.is_configurable()` check.

**Comment by romanarust** [comment]
True, this has to move to compas level, will migrate the issue
