### ISSUE TITLE
Grasshopper components for mac

### ISSUE THREAD

**Issue by simonmaris** [compas-dev/compas_fab#276]
This is not so much a feature request, but more of an inquiry..

After trying to get the grasshopper components working on Rhino for Mac, I finally figured out that the installation is currently skipped by looking at the [source code](https://github.com/compas-dev/compas_fab/blob/main/src/compas_fab/rhino/install.py). 

I did obviously try to install them manually out of curiosity, only to find lot's of errors and Grasshopper breakpoints. 

So far, so good. Maybe this issue could be a place to discuss the problems and try to find a way collectively to make this a reality? Have you encountered really deep issues with this or is it _just_ a question of fixing some bugs and making it compatible.

I would like to use this in workshops with students and more and more have made the move to grasshopper for mac in recent months. 

Also: thank you so much for all the awesome work in the compas ecosystem!

**Comment by gonzalocasas** [comment]
Fixed in #294
