### ISSUE TITLE
Check for IK solution without breaking (ROS)

### ISSUE THREAD

**Issue by laurend** [compas-dev/compas_fab#278]
Is there a way to check if an IK solution exists without breaking the script and throwing an error? 
If so, could an example of how to do this be added to the docs? 

For example, I would like to be able to first check if solution exists and then offer an alternative frame if it doesn't.

**Comment by beverlylytle** [comment]
The usual way to handle exceptions in Python is with a `try`-`except` clause.  For example, if `frames` is a list of frames you'd like to check inverse kinematic solutions for in decreasing order of preference:
```
for frame in frames:
    try:
        ik_solution = client.inverse_kinematics(robot, frame)
        break
    except BackendError:
        print("trying again")
else:
    print("No ik solution found.")
```
Would something like that suit your purposes?

**Comment by laurend** [comment]
Yes... `BackendError` works. Thanks!

**Comment by beverlylytle** [comment]
Great!
