### ISSUE TITLE
Threading issue when using MoveIt services on mac

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas_fab#295]

**Comment by beverlylytle** [comment]
On a Mac, in some circumstances, when 4 or more calls are made to a ROS service with roslibpy, on the third or fourth call, the script hangs.  For example `compas_fab/docs/examples/03_backends_ros/files/04_append_collision_meshes.py` will hang when run from the terminal.  (It however runs fine in the context of `invoke test --doctest --codeblock`.)
