### ISSUE TITLE
PyBullet client: check if collision meshes are convex

### ISSUE THREAD

**Issue by inesariza** [compas-dev/compas_fab#322]
# Feature Request

As a user of the PyBullet client, I want to check if collision meshes are convex before any collision detection operation is performed.

## Details

**Is your feature request related to a problem? Please describe.**
Even if using this client often one could forget the implicit rule that meshes need to be convex. It would be great to check for this automatically.

**Describe the solution you'd like**
Ideally, when adding collision meshes to the scene, concave meshes raise a warning telling the user that a convex hull operation will be performed. The user can then decide if continuing with the convex hull or updating inputs (decomposing the input meshes to make them convex). 

**Describe alternatives you've considered**
Alternatively, the user gets a warning message for each convex hull operation including the name of the mesh that has been wrapped.

**Comment by inesariza** [comment]
thank you for your assessment and reply, @beverlylytle! 

Sounds like the convexity check would be costly and would not really solve the problem (i.e., that we want convex meshes). 

Having the option of applying V-HACD would be best for most cases. For this solution then, the only limitation is that we need .objs instead of compas meshes?

**Comment by beverlylytle** [comment]
Yes.  What could be done is adding a flag somewhere... maybe on `load_robot` and also the planning scene methods, which would apply V-HACD when the flag is True.  (Behind the scenes, the `PyBulletClient` already does a lot of converting compas meshes to obj files to load into the pybullet server.)  So, handling convexity would not be automatic, but semi-automatic ;)
