### ISSUE TITLE
Clean up the broken Class and Function links in docstrings

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas_fab#413]
**Describe the bug**
Some of the docstrings has 
```
``Configuration``
:Class:`Configuration`
```

will replace them with
```
:Class:`~compas_robots.Configuration`
```

Will probably do other replacements as well, but this is the first one I noticed.

**Comment by yck011522** [comment]
We can discuss whether we want to hide the `compas_robot.` part with the `~` directive. I prefer hiding it.

**Comment by gonzalocasas** [comment]
hiding ! +1
