### ISSUE TITLE
add_collision_mesh as Service

### ISSUE THREAD

**Issue by romanarust** [compas-dev/compas_fab#46]
It would be nice to have the `scene.add_collision_mesh(collison_mesh)` implemented as Service (blocking call) at least on compas_fab level, so that one can be sure MoveIt has received the mesh before making path planning requests.

**Comment by romanarust** [comment]
Comment connected to this issue
https://github.com/compas-dev/compas_fab/issues/32#issuecomment-456610133

**Comment by gonzalocasas** [comment]
Overlaps with #95, so I'm closing this in favor of the other one.
