### ISSUE TITLE
Converting compas meshes to pybullet objects

### ISSUE THREAD

**Issue by yijiangh** [compas-dev/compas_fab#61]
This is the immediate next step after collision objects' meshes are fetched back from the planning scene (#60). The proposed util function will convert the compas meshes into pybullet bodies. This function will reside in the `ros.plugins_choreo.ChoreoPlanner` (#55 ).

**Comment by gonzalocasas** [comment]
The implementation of the conversion of `compas.datastructures.Mesh` to pybullet bodies could eventually live in a `compas_fab.backends.pybullet` package instead of inside the Choreo planner.

**Comment by yijiangh** [comment]
@gonzalocasas That's a great idea! Also #59 should also reside in `compas_fab.backends.pybullet`.

**Comment by gonzalocasas** [comment]
Already merged into master! :)
