### ISSUE TITLE
Document confusion

### ISSUE THREAD

**Issue by xarthurx** [compas-dev/compas_fab#68]
https://gramaziokohler.github.io/compas_fab/latest/examples/03_backends_ros/07_ros_create_urdf_ur5_with_measurement_tool.html

For the doc here, the `3.5.3.1 Explanation` is inbetween `3.5.3.3` and `3.5.3.4`, which is quite confusing.
The text seems also not to explain what is above the section, but more to describe what is done afterwards.

Perhaps consider some rephrasing?

**Comment by gonzalocasas** [comment]
(fixed on the doc's source, will be published to the website on the next release)
