### ISSUE TITLE
installation fails but conda clean --all fixes it

### ISSUE THREAD

**Issue by inesariza** [compas-dev/compas_fab#71]
compas_fab installation fails in fresh conda environment.

`conda install -c conda-forge compas_fab`

error:
```
ClobberError: The package 'conda-forge::compas_fab-0.6.0-py37_0' cannot be installed due to a
path collision for 'lib/site-packages/compas_fab/utilities/__pycache__/numbers.cpython-37.pyc'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.
```

also tried this in an existing environment with `compas_fab 0.7.2` working, in this case the error points to `bcrypt` not finding a path.

`conda clean --all` and then 
`conda install -c conda-forge compas_fab` works

**Comment by gonzalocasas** [comment]
@inesariza I wasn't able to reproduce this; I tried a few things but they all worked. Does it still happen on your machine?
