### ISSUE TITLE
Make planning scene methods synchronous

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas_fab#95]
Currently, all planning scene modifications of the ROS backend (add/remove/append collision objects) are sent via topics, so there's no feedback about whether the operation was completed or not, leading to the proliferation of `time.sleep()` all around and the assumption that after waiting a bit, the operation will be finished.

However, ROS has a service to apply planning scene changes in deltas (diffs), which is probably much better for this case. We should switch the current implementation with a service-based one (which can also be used as blocking calls), to simplify user's code.

**Comment by beverlylytle** [comment]
Requires implementing Octomap stuff.
